### ISSUE TITLE
Errors in weasyprint container log with 62.4.2 after last bug is fixed now

### ISSUE THREAD

**Issue by nweidemann** [SchweizerischeBundesbahnen/weasyprint-service#56]
### Current Behavior

PDF Export now works in general, but there are several errors.
Can you please have a look on them?

[weasyprint_container.log](https://github.com/user-attachments/files/16906788/weasyprint_container.log)

### Expected Behavior

I think those errors should not occcur

### Steps To Reproduce

Export a document to PDF

![image](https://github.com/user-attachments/assets/cb44a7fb-5723-459f-b60d-5084d3a3786a)

**Comment by nweidemann** [comment]
comment from our customer..

I just generated the PDF again successfully, but unfortunately there is an issue with result itself. The SVG files are cut off somewhere in the middle. I just took a look and this wasn't the case about a week ago. I assume this could be related to the chrome issue as SVGs are rendered in the container using chrome

**Comment by grigoriev** [comment]
@nweidemann,

we have created some issues we have found in provided log:

- [log contains error messages during SVG conversion](https://github.com/SchweizerischeBundesbahnen/weasyprint-service/issues/60)
- [error messages in log for getting resources](https://github.com/SchweizerischeBundesbahnen/weasyprint-service/issues/61)

Regarding your last comment. Could you provide us with the log from customer when some SVG files are cut off as well?

**Comment by Jumas** [comment]
@nweidemann 

Also could you please provide how the reference "https://awspoldsdtu.polarion-iat.comp.db.de/polarion/icons/default/enums/req_status_approved.gif" appears in your initial document. Using some css property?

**Comment by grigoriev** [comment]
All the findings should be fixed with PDF-Exporter v7.1.1 and WeasyPrint Service v62.4.5.

@nweidemann could you please test it and share the results?

**Comment by nweidemann** [comment]
Hi, sorry for the late Reply. As Ralf Smolarek from SBB told me that he will take over, I didn't took care any longer of the tickets.
We are running PDFExporter 5.7.0 with Weasyprint aaS in Docker in version 62.4.3. Our customer told us that everything is fine now.
thx for your support!

Regards,
Niko Weidemann
DB Systel GmbH
